from distutils.core import setup, Extension

classifierList = [ 'Cmodule', 'Cmodule::dateString', 'Resource::bgm::댐.WAV', 'Resource::bgm::따라란.WAV',
                  'Resource::bgm::띠딩.WAV', 'Resource::bgm::띠리리링.WAV',
                  'Resource::bgm::띵.WAV', 'Resource::bgm::보석이빛날때.WAV',
                  'Resource::bgm::뽁.WAV', 'Resource::bgm::뿅.WAV',
                  'Resource::bgm::샤라락.WAV','Resource::Image::background.png',
                  'Resource::Image::bear.png','Resource::Image::bear2.png',
                  'Resource::Image::book.png','Resource::Image::book_stock.png',
                  'Resource::Image::book2.png','Resource::Image::book3.png',
                  'Resource::Image::book4.png','Resource::Image::book5.png',
                  'Resource::Image::edit.png','Resource::Image::icon.ico',
                  'Resource::Image::NoImage.png','Resource::Image::rating_bad.PNG',
                  'Resource::Image::rating_default.PNG','Resource::Image::rating_good.PNG',
                  'Resource::Image::rating_normal.PNG','Resource::Image::remove.png',
                  'Resource::Image::save.png','Resource::Image::start_Scene.png']

setup(name='bookreview',
      version='1.0',
      ext_package='pkg',
      classifiers = classifierList,
      packages=['Cmodule','Resource','Resource.bgm','Resource.Image'],
      #ext_modules=[Extension('bookreview.Cmodule', ['dateString.pyd'])],
      # data_files=[('bookreview.Resource.bgm',['댐.WAV','따라란.WAV','띠딩.WAV',
      #                                         '띠리리링.WAV','띵.WAV','보석이빛날때.WAV',
      #                                         '뽁.WAV','뿅.WAV','샤라락.WAV']),
      #             ('bookreview.Resource.Image',['background.png','bear.png',
      #                                           'bear2.png','book.png','book_stock.png',
      #                                           'book2.png','book3.png','book4.png',
      #                                           'book5.png','edit.png','icon.ico',
      #                                           'NoImage.png','rating_bad.PNG',
      #                                           'rating_default.PNG','rating_good.PNG',
      #                                           'rating_normal.PNG','remove.png',
      #                                           'save.png','start_Scene.png'])],
      py_modules=['Bestseller_Search_engine','BestsellerGUI',
                  'book','book_search_engine','bookManager','bookSearchGUI',
                  'editGUI','Library','Library_search_engin','LibrarySearchGUI',
                  'Main','rating_image','RecordBookGUI','recordDetailGUI',
                  'Sounds','statisticsGUI','urlImage',]
      )
